[project]
name = "blender-models"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mapbox-earcut>=2.0.0",
    "matplotlib>=3.10.9",
    "shapely>=2.1.2",
    "trimesh>=4.12.2",
]

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
